export const GET_PRODUCT = "GET_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const ADD_ONE = 'ADD_ONE'
export const SUBTRACT_ONE = 'SUBTRACT_ONE'

export const GET_PRODUCT_FROM_DB = "GET_PRODUCT_FROM_DB";
export const ADD_PRODUCT_TO_DB = "ADD_PRODUCT_TO_DB"
export const DELETE_PRODUCT_FROM_DB = "DELETE_PRODUCT_FROM_DB"
export const ADD_ONE_TO_DB = 'ADD_ONE_TO_DB'
export const SUBTRACT_ONE_FROM_DB = 'SUBTRACT_ONE_FROM_DB'

